spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 611001
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
bookstore:
  openapi:
    dev-url: http://localhost:8080
jwt:
  expiration: 1200000
  secret: fkaafa1r88)_402492fls;l2=040;fs'104jfjlf1804180
springdoc:
  swagger-ui:
    tags-sorter: alpha
  writer-with-order-by-keys: true