spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQLDB_DATABASE}?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
bookstore:
  openapi:
    dev-url: http://localhost:8080
jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
springdoc:
  swagger-ui:
    tags-sorter: alpha
  writer-with-order-by-keys: true